version: '3'
services:
  vanilla-local:
    container_name: vanilla-local
    env_file:
      - ./vanilla.env
    build:
      context: .
      args:
        - VANILLA_VERSION=3.3
    ports:
      - 80:80