version: '3'
services:
  mysql-local:
    image: mysql
    container_name: mysql-local
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=vanilladb
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
  vanilla-local:
    container_name: vanilla-local
    build:
      context: .
      args:
        - VANILLA_VERSION=3.3
    ports:
      - 80:80
    links:
      - mysql-local
