version: '3'
services:
  vanilla-forums:
    image: vanilla-forums:latest
    container_name: vanilla-forums
    env_file:
      - ./vanilla.env
    build:
      context: .
      args:
        - ENV
        - VANILLA_VERSION=3.3
        - CI_DEPLOY_TOKEN
    links:
      - tideways-daemon
    ports:
      - 80:80
  tideways-daemon:
    container_name: tideways-daemon
    build:
      context: ./tideways-daemon
    ports:
      - 9135:9135