version: '3'
services:
  vanilla-forums:
    image: vanilla-forums:latest
    container_name: vanilla-forums
    env_file:
      - ./vanilla.env
    build:
      context: .
      args:
        - ENV='dev'
        - VANILLA_VERSION=3.3
        - CI_DEPLOY_TOKEN
        - BRANCH
        - TIDEWAYS_ENV
    ports:
      - 80:80
      - 443:443