version: '3'
services:
  vanilla-forums:
    image: vanilla-forums:latest
    container_name: vanilla-forums
    env_file:
      - ./vanilla.env
    build:
      context: .
      args:
        - VANILLA_VERSION=3.3
    ports:
      - 80:80