version: '3'
services:
  vanilla-forums:
    links:
      - tideways-daemon
  tideways-daemon:
    container_name: tideways-daemon
    build:
      context: ./tideways-daemon
    ports:
      - 9135:9135